server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log


#Using Json Config With Log Options: tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
  - output:
      source: output

#Using docker socket to grab docker logs instead of JSON output
# - job_name: docker
#   docker_sd_configs:
#     - host: unix:///var/run/docker.sock
#       refresh_interval: 5s
#   relabel_configs:
#     - source_labels: ['__meta_docker_container_name']
#       regex: '/(.*)'
#       target_label: 'container'
#     - source_labels: ['__meta_docker_network_name']
#       target_label: 'network'

#Custom Log Folder - Make sure to mount the location in __path__
# - job_name: userlogs
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: userlogs
#       __path__: /opt/logs/*log

